local icons = {}

-- stylua: ignore
icons = {
  misc = {
    dots = "󰇘",
    comp = " ",
    lan = "󰌗",
    localhost = "󰌢",
    running_animated   = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" },
  },
  ft = {
    octo = "",
    git = "󰊢",
    devcontainer = "",
    angular = "󰚲",
  },
  statusline = {
    root = "󱉭",
    separator = "",
    spell = " ",
    debug = "  ",
    clock = " ",
    lsp = " ",
    lsp_disabled = "󱏎 ",
  },
  dap = {
    Stopped             = { " ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint          = " ",
    BreakpointCondition = " ",
    BreakpointRejected  = { " ", "DiagnosticError" },
    LogPoint            = " ",
  },
  copilot = {
    enabled  = " ",
    sleep    = " ", -- auto-trigger disabled
    disabled = " ",
    warning  = " ",
    unknown  = " ",
  },
  diagnostics = {
    Error  = " ",
    Warn   = " ",
    Hint   = " ",
    Info   = " ",
    prefix = "●",
  },
  git = {
    added    = " ",
    modified = " ",
    removed  = " ",
    gutter = {
      change = "▎",
      delete = "",
    },
  },
  kinds = {
    Array         = " ",
    Boolean       = "󰨙 ",
    Class         = " ",
    Codeium       = "󰘦 ",
    Color         = " ",
    Control       = " ",
    Collapsed     = " ",
    Constant      = "󰏿 ",
    Constructor   = " ",
    Copilot       = " ",
    Enum          = " ",
    EnumMember    = " ",
    Event         = " ",
    Field         = " ",
    File          = " ",
    Folder        = " ",
    Function      = "󰊕 ",
    Interface     = " ",
    Key           = " ",
    Keyword       = " ",
    Method        = "󰊕 ",
    Module        = " ",
    Namespace     = "󰦮 ",
    Null          = " ",
    Number        = "󰎠 ",
    Object        = " ",
    Operator      = " ",
    Package       = " ",
    Property      = " ",
    Reference     = " ",
    Snippet       = "󱄽 ",
    String        = " ",
    Struct        = "󰆼 ",
    Supermaven    = " ",
    TabNine       = "󰏚 ",
    Text          = " ",
    TypeParameter = " ",
    Unit          = " ",
    Value         = " ",
    Variable      = "󰀫 ",
    -- clangd specific
    Compound             = "",
    Recovery             = "",
    TranslationUnit      = "",
    PackExpansion        = "",
    TemplateTypeParm     = "",
    TemplateTemplateParm = "",
    TemplateParamObject  = "",
  },
  roles = {
    type                  = " ",
    declaration           = " ",
    expression            = " ",
    specifier             = " ",
    statement             = " ",
    ["template argument"] = " ",
  },
  tests = {
    passed             = "󰗠 ",
    running            = "󰐌 ",
    failed             = "󰅙 ",
    skipped            = "󰮍 ",
    unknown            = "󰋗 ",
    non_collapsible    = "─",
    collapsed          = "─",
    expanded           = "╮",
    child_prefix       = "├",
    final_child_prefix = "╰",
    child_indent       = "│",
    final_child_indent = " ",
    watching           = "󰮔 ",
    test               = "󰙨 ",
    notify             = "󰙨 ",
  },
}

return icons
