[settings]
default_target_type = "symbolic"

[nvim.files]
"nvim" = "~/.config/nvim"

[fish.files]
"fish" = "~/.config/fish"

[ghostty.files]
"ghostty" = "~/.config/ghostty"

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[zellij.files]
"zellij" = "~/.config/zellij"

[tmux.files]
"tmux/tmux.conf" = "~/.config/tmux/tmux.conf"

[bat.files]
"bat" = "~/.config/bat"

[btop.files]
"btop" = "~/.config/btop"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[mcphub.files]
"mcphub" = "~/.config/mcphub"

[git.files]
"git/gitconfig" = "~/.gitconfig"

[amethyst.files]
"amethyst/amethyst.yml" = "~/.amethyst.yml"

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[hatch.files]
"hatch" = "~/.config/hatch"

[ipython.files]
"ipython/ipython_config.py" = "~/.ipython/profile_default/ipython_config.py"

[iterm2.files]
"iterm2/com.googlecode.iterm2.plist" = "~/.config/iterm2/com.googlecode.iterm2.plist"

[kitty.files]
"kitty" = "~/.config/kitty"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
