function load --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LAD_OPTIONS $EXA_LO_OPTIONS' --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAD_OPTIONS $EZA_LO_OPTIONS' --description 'alias load eza $EZA_STANDARD_OPTIONS $EZA_LAD_OPTIONS $EZA_LO_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAD_OPTIONS $EZA_LO_OPTIONS $argv
        
end
