function ltaai --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LT_OPTIONS' --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LT_OPTIONS' --description 'alias ltaai eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LT_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LT_OPTIONS $argv
        
end
