function ltid --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LID_OPTIONS $EXA_LT_OPTIONS' --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LID_OPTIONS $EZA_LT_OPTIONS' --description 'alias ltid eza $EZA_STANDARD_OPTIONS $EZA_LID_OPTIONS $EZA_LT_OPTIONS'
  eza $EZA_STANDARD_OPTIONS $EZA_LID_OPTIONS $EZA_LT_OPTIONS $argv
        
end
